FROM anapsix/alpine-java:jre7

ADD https://socrata-oss.ci.cloudbees.com/job/opendj/lastSuccessfulBuild/org.forgerock.opendj\$opendj-server/artifact/org.forgerock.opendj/opendj-server/2.6.0/opendj-server-2.6.0.zip /opt/
RUN cd /opt/ && unzip opendj-server-2.6.0.zip

ENV ROOT_USER_DN cn=Directory\ Manager
ENV ROOT_USER_PASS passpass
ENV BASE_DN dc=example,dc=org

WORKDIR /opt/opendj
RUN ./setup --cli -v \
  --ldapPort 1389 \
  --ldapsPort 1636 \
  --adminConnectorPort 4444 \
  --rootUserDN "$ROOT_USER_DN" \
  --rootUserPassword $ROOT_USER_PASS \
  --generateSelfSignedCertificate \
  --no-prompt --noPropertiesFile \
  --doNotStart

ADD start /start
ENTRYPOINT ["/start"]
CMD ["start"]
EXPOSE 1389 1636 4444
