#!/bin/bash

set -e

COMMAND=${1:-start}

ulimit -n 10240

function persist_dir {
    local link=/opt/opendj/$1
    local target=/data/opendj/$1
    if [ -d /data ] && [ ! -L $link ]; then
        if [ ! -d $target ]; then
            echo "Configuring persistence of opendj/$1..."
            mkdir -p `dirname $target`
            mv $link $target
        else
            echo "Restoring persisted opendj/$1..."
            rm -rf $link
        fi

        ln -f -s $target $link
    fi
}


function import_ldifs {
    LDIF_DIR=/data/opendj/ldif
    if [ -d $LDIF_DIR ]; then
        IMPORTED_DIR=/data/opendj/imported-ldif
        mkdir -p $IMPORTED_DIR
        for LDIF in $LDIF_DIR/*.ldif ; do
            FNAME=$(basename $LDIF)
            echo "Importing $FNAME..."
            bin/ldapmodify -p 4444 -D "$ROOT_USER_DN" -w $ROOT_USER_PASS -a -X -Z -f $LDIF

            # TODO: support offline import for speed
            # bin/import-ldif --includeBranch $BASE_DN --backendID userRoot --ldifFile $LDIF --rejectFile $IMPORTED_DIR/${FNAME}.reject --skipFile $IMPORTED_DIR/${FNAME}.skip
            # test ! -s $IMPORTED_DIR/${FNAME}.reject && rm $IMPORTED_DIR/${FNAME}.reject
            # test ! -s $IMPORTED_DIR/${FNAME}.skip && rm $IMPORTED_DIR/${FNAME}.skip
            mv $LDIF $IMPORTED_DIR
        done
    fi
}


for directory in db config logs bak; do
    persist_dir $directory
done


case $COMMAND in
    start )
        /opt/opendj/bin/start-ds --nodetach ;;
    passwd )
        echo "not yet supported" || exit 1 ;;
    configure )
        /opt/opendj/bin/start-ds
        echo "Creating userRoot backend with base-dn:$BASE_DN"
        /opt/opendj/bin/dsconfig create-backend --backend-name userRoot --type=local-db --set base-dn:$BASE_DN --set enabled:true --noPropertiesFile --no-prompt -p 4444 --trustAll -D "$ROOT_USER_DN" -w $ROOT_USER_PASS
        /opt/opendj/bin/stop-ds
        echo "Complete."
        ;;
    import )
        /opt/opendj/bin/start-ds
        import_ldifs
        /opt/opendj/bin/stop-ds
        ;;
    shell )
        /bin/bash ;;
    * )
        echo "ERROR: Not a valid command: $COMMAND" || exit 1 ;;
esac
